# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=100)),
                ('abbreviations', models.CharField(max_length=100)),
                ('contract_name', models.CharField(max_length=100)),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('order_company', models.CharField(max_length=100)),
                ('order_company_representative', models.CharField(max_length=100)),
                ('amount_of_order', models.BigIntegerField()),
                ('amount_of_order_type', models.CharField(max_length=45)),
                ('category1', models.CharField(max_length=45)),
                ('category2', models.CharField(max_length=45)),
                ('category3', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.Project'),
        ),
    ]
